[package]
name = "top-shooter-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
top-shooter-contracts = { path = "../top-shooter-contracts" }
top-shooter-control = { path = "../top-shooter-control" }
top-shooter-store = { path = "../top-shooter-store" }
uuid.workspace = true
url.workspace = true

[dev-dependencies]
sqlx.workspace = true
